### ISSUE TITLE
FireFox on Linux sqrl:// scheme inconsistent

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#102]
On FireFox the sqrl:// scheme doesn't work sometimes, other times it works when you right click open in new window.
We need to find a more reliable implementation of it, perhaps since we have CPS we can have CPS "wake up" the UI on connection?
Also we can probably look for a better , more , alternative to the sqrl:// registration for firefox...

No idea

**Comment by alexhauser** [comment]
Linking a forum post that might be relevant here:
https://sqrl.grc.com/threads/linux-testing-feedback.1109/post-9401

**Comment by dxcSithLord** [comment]
I found this that should also be helpful on how to register Protocol Handler
[https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler/Web-based_protocol_handlers) 
and this
[https://support.mozilla.org/en-US/questions/1169576](https://support.mozilla.org/en-US/questions/1169576)

**Comment by dxcSithLord** [comment]
I also noticed that there seems to be a problem with opening the 127.0.0.1:25519 port - it doesn't check that the port is in TIME_WAIT state and should be able to close the port, without TIME_WAIT (I have seen this referenced, but can't remember details - I will try and find out more).
Currently on my Ubuntu 18.04.04 machine, I can see a CLOSE_WAIT state on the port.  The SQRL application is running but this is the current port state:
`ss | grep 127.0.0.1`
`Netid    State  Recv-Q   Send-Q   Local Address:Port  Peer Address:Port`
`tcp  CLOSE-WAIT  1   0   127.0.0.1:25519     127.0.0.1:48530  `

I would suggest checking the code where the port is opened and check for error on open, put in a delay, or warning, or both.  On exit, see if there is a way to force the port to close, without waiting for a response from the other end.  (I haven't restarted my browser in a while).

I am going to try the latest beta (P.S. ping SithMagic a note on how to upgrade, or where this can be found) on a "fresh" Firefox state - after making a snapshot so I can repeat the tests.

**Comment by alexhauser** [comment]
@dxcSithLord, I guess it would be helpful if you could run the latest code off the master branch for testing instead of having to wait for a release. If you would like to try that, here are the basic steps to do so:

First, you'd have to install the .NET Core SDK:
https://docs.microsoft.com/en-us/dotnet/core/install/sdk

Then install git, clone the repo, build and run:
```
git clone https://github.com/sqrldev/SQRLDotNetClient.git
cd SQRLDotNetClient/SQRLDotNetClientUI
donet build && dotnet run
```

**Comment by dxcSithLord** [comment]
Thanks for that - Here is an strace file that shows all of the system calls  when just launching and exiting the latest Beta version.  The file is plain text.  For information on how to read (or more detailed diagnostics), see [https://www.cyberciti.biz/faq/howto-use-linux-truss-strace-command/](https://www.cyberciti.biz/faq/howto-use-linux-truss-strace-command/).  Dtrace is another command that could enlighten what is happening, but that is a bit more involved, than 
`strace -o client_UI_strace.txt ./SQRLDotNetClientUI`

[client_UI_strace.txt](https://github.com/sqrldev/SQRLDotNetClient/files/4500260/client_UI_strace.txt)

You can search (grep) the file for open/read/write actions.  Failed attempts have "ENOxxx" where xxx is the error type.

I will try with the latest version - same thing.

**Comment by dxcSithLord** [comment]
With the latest source from master, here is the dotnet lanched strace file for start and stop - still no port 25519 listening:
[dotnet_built_client_ui_strace2.txt](https://github.com/sqrldev/SQRLDotNetClient/files/4500362/dotnet_built_client_ui_strace2.txt)

**Comment by dxcSithLord** [comment]
Daft question, why do I see port 127.0.0.1:13000 opened when I run the program and the public class IPCServer in the code has the TcpListener set with a default of 13000, rather than 25519?  I understand from the comments this is to prevent multiple instances, but this isn't the method employed by the GRC client (no port 13000 listening).  Alternative on Unix/Linux, you can create a special file "semaphore" that can do this, or it could even be a FIFO pipe for Inter Process communication - there is even a command "ipcs" to show inter-process communication status.  This would be a better method and from the IPCSserver class, it would suggest that it is also available on Windows too.

**Comment by josegomez** [comment]
@dxcSithLord 
We already use a Mutex (a semaphore) to allow only once instance of the app to run. The issue is we need to send the URL data to that instance from the current (new) instance that is instanciated by the sqrl:// scheme.

In order to avoid too much platform specific code we are using TCP for Inter Process Communication. Mac, Linux and Windows all handle inter Process communication differently (natively) and it would require a lot of different specific code for each platform.

Using Tcp allows us to keep it standard, this allows us to just use TCP to communicate with the running process, it listens only on 127.0.0.1 so it shouldn't pose a threat externally unless you have some malware or something else running on your computer.

I suppose we could use the already existing CPS Server for this, but it seemed gross to mix context that way

Thoughts @alexhauser ?

**Comment by josegomez** [comment]
> With the latest source from master, here is the dotnet lanched strace file for start and stop - still no port 25519 listening:
> [dotnet_built_client_ui_strace2.txt](https://github.com/sqrldev/SQRLDotNetClient/files/4500362/dotnet_built_client_ui_strace2.txt)

Regarding this we don't start listening on 25519 until we receive an Auth Request. There is no need to have this sitting there open listening doing much of nothing.

When an Auth request is received via a SQRL:// scheme invocation we start listening on 25519

**Comment by josegomez** [comment]
Oops wrong button

**Comment by dxcSithLord** [comment]
I thought that would be the case, but where does port 25519 get opened?
If the port is not open, you are not going to receive a request via that port, which is what the demo page is doing.  The application association handles the URL getting opened in new tab action, but that can lose traction with the original page.
Why not open port 25519 and use that instead of port 13000, this would be consistent behaviour with the GRC client, which is always listening on port 25519.

**Comment by dxcSithLord** [comment]
Also when you do receive a request via port 25519, the application can switch to visible from hidden and any repeat launch will see that the port is already open and can pass the request directly to that already open port (perhaps with an additional parameter, or not)?

**Comment by josegomez** [comment]
> I thought that would be the case, but where does port 25519 get opened?
> If the port is not open, you are not going to receive a request via that port, which is what the demo page is doing. The application association handles the URL getting opened in new tab action, but that can lose traction with the original page.
> Why not open port 25519 and use that instead of port 13000, this would be consistent behavior with the GRC client, which is always listening on port 25519.

When a request is invoke via SQRL:// it launches a new instance of SQRL. Which using the Mutex looks to see if there is a running version. If there is, it passed in an authentication request with the URL which launches CPS (25519) and connects it to the client (current browser instance) so nothing is lost there.

If it doesn't see a running instance of the app then an Authentication request is received and launched again CPS (25519) is opened and established which causes the Browser client to connect and associate so nothing is lost there.

But yes Steve's client is always listening on 25519 and we could do the same but I don't see the advantage

**Comment by josegomez** [comment]
> Also when you do receive a request via port 25519, the application can switch to visible from hidden and any repeat launch will see that the port is already open and can pass the request directly to that already open port (perhaps with an additional parameter, or not)?

We wrote the SQRL and CPS implementations as an independent library (outside of the Client Implementation) this means that SQRL library and the corresponding CPS implementation don't need to know ANYTHING about the UI Client
But that means that requests received in CPS aren't aware of the UI screen and thus can't easily awaken the UI from CPS.

I agree this would be cool so maybe we could add an enhancement to create a CPS Event that the client can subscribe to to get awoken from a CPS connection, again assuming we move to start CPS right away with the client and not when an Auth request is created. This could also mitigate some of the sqrl:// invocation issues in Linux if the client is already running.

My fear though is that we'll end up in a race condition (like steve client does) where the sqrl:// invokation and the 25519 invocation "race" to figure out which one handles auth and that can lead to weird behavior (again particularly on linux where FireFox will prompt you about sqrl:// yet the client is already well on its way)

@alexhauser thoughts?

**Comment by josegomez** [comment]
@dxcSithLord 
Added #130 to look at some of your concerns

**Comment by dxcSithLord** [comment]
OK - I will test some of the protocol settings for Linux to see if I can get that working consistently, based on the test published previously and advise on findings.

**Comment by dxcSithLord** [comment]
Found useful information on protocol handler settings for Linux and Mac OS - put links on #130.  @josegomez  I missed the bit about mutex semaphore earlier.

**Comment by alexhauser** [comment]
@dxcSithLord 
I guess that should have been a thumbs-up by @josegomez 😎

**Comment by josegomez** [comment]
Yup fat finger

**Comment by alexhauser** [comment]
Finally finding some time to look at this, the solution to this mistery turns out to be quite simple:

```javascript
// Linux/WINE desktop environments lack the uniform means for registering scheme handlers.
// So when we detect that we're running under Linux we disable the invocation of SQRL with
// the "sqrl://" scheme and rely upon upon the localhost server --- UNLESS we detect 'sqrl'
// present in the user-agent header which gives us permission to invoke with the sqrl:// scheme.
window.onload = function() {
    if ((navigator.userAgent.match(/linux/i)) && !(navigator.userAgent.match(/sqrl/i)) && !(navigator.userAgent.match(/android/i)))
    {        // if we're on Linux, suppress the sqrl:// href completely
        document.getElementById("sqrl").onclick = function() { sqrlLinkClick(this); return false; };
    }
 }
```
So Steve turns off the `sqrl://` link invokation on the demo page for Linux ON PURPOSE, as long as no `sqrl` string is present in the user agent header. I don't think we can fix this without Steve, can we? 

At least, we know now that everything is working as it should on our side.

CC @josegomez, @dxcSithLord

**Comment by josegomez** [comment]
Nice!!!!!!

**Comment by alexhauser** [comment]
I've pinged Steve on Twitter and asked him if he would consider removing the blocking of the `sqrl://` scheme invocation for Linux on the demo page. I'll report as soon I receive any feedback.

**Comment by josegomez** [comment]
Sounds good, can't we just push sqrl as part of the user agent? I'm guessing that's not trival

**Comment by alexhauser** [comment]
> Sounds good, can't we just push sqrl as part of the user agent? I'm guessing that's not trival

Even if we could, it would feel wrong on so many levels to have to mess around with the browser's user agent header.

**Comment by dxcSithLord** [comment]
I have and another search into this and the answer may be in DBUS interaction, since this is part of the freeDesktop.org "standard", this may be different on Unix that does not use freeDesktop standard, but that list is short (hopefully).  Since Linux is based on "Free", this should cover all Linux flavors.  
To make life more interesting "SCHEMA" in Linux/Unix refers to application schemas, not just URI/URL application associations, that is trying to be mapped.  
See [https://dbus.freedesktop.org/doc/dbus-specification.html](https://dbus.freedesktop.org/doc/dbus-specification.html) for spec.  This is used by Gnome and other desktops in Linux environments and SHOULD be picked up by any browser on the machine.  It will also allow you to use sockets to talk between CPS and UI, perhaps.
Before you ask, is it compatible with dotnet, see [https://github.com/tmds/Tmds.DBus](https://github.com/tmds/Tmds.DBus) and [https://developers.redhat.com/blog/2017/09/18/connecting-net-core-d-bus/](https://developers.redhat.com/blog/2017/09/18/connecting-net-core-d-bus/).  Worth investigating.  Hope this helps

**Comment by alexhauser** [comment]
@dxcSithLord, thanks for your input. As it turned out, what we did on Linux was always working as expected, but Steve has deliberately crippled the demo site's ability to invoke the `sqrl://` scheme on Linux (see posts above).

I will post a PR shortly that will change the way we deal with CPS, which effectively will work around this issue. Stay tuned.
