### ISSUE TITLE
Detect No CPS/ MITM Mitigation according to Identity Specs

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#117]
Currently we have a flag set as "WARN" of possible MITM Attack in the identity but we aren't checking if CPS Is indeed being used or not.
We should (check the spec) and implement accordingly I haven't verified what that is exactly, but I believe Steve's client yells (warns) if you try to auth on Same Device and don't / can't use CPS.

**Comment by alexhauser** [comment]
For the record, it's those two identity flags that are relevant for this issue:

--------------------------------------------------------

Flag `0x0010`
> Warn of possible MITM attack: When set, this bit instructs the SQRL client to
notify its user when the web server indicates that an IP address mismatch exists
between the entity that requested the initial logon web page containing the SQRL
link URL (and probably encoded into the SQRL link URL's “nut”) and the IP
address from which the SQRL client's query was received for this reply. 

... which is connected to TIF bit `0x04`:
> IPs matched: When set, this bit indicates that the IP address of the entity which
requested the initial logon web page containing the SQRL link URL (and probably
encoded into the SQRL link URL's “nut”) is the same IP address from which the SQRL
client's query was received for this query & reply. Note that the server MUST retain the
IP associated with the original SQRL URL, not any subsequent query, and compare each
query IP address against that original IP address. 

--------------------------------------------------------

Flag `0x0100`
> Warn of non-CPS authentication: When set, this bit instructs the SQRL client to
notify its user whenever a non-CPS authentication is attempted. Since CPS
provides extremely strong protection against website spoofing—which is a
particularly significant concern for SQRL due to its high degree of automation and
presumed automatic provision of security—this flag must default to enabled.

**Comment by alexhauser** [comment]
I'm working on this one @josegomez, but ran into a problem:

When testing the MITM stuff on https://www.grc.com/sqrl/nospoof.htm using the red "Spoof with SQRL" button, I get a command failed (TIF `0x40`) which prevents me from testing the IP mismatch. Any idea what's going on there?

**Comment by josegomez** [comment]
Weird not sure I’ll poke about

**Comment by josegomez** [comment]
@alexhauser 
Here's the issue
![image](https://user-images.githubusercontent.com/420837/81311075-f0ce6e80-9052-11ea-9892-8e8c0b27cd88.png)

So on the Authentication Model line 337
https://github.com/sqrldev/SQRLDotNetClient/blob/d43ebab283ac17d5638c5dfe95f17e30c58fede9/SQRLDotNetClientUI/ViewModels/AuthenticationViewModel.cs#L336-L349

We check for Command Failed 40 but we aren't checking the IPMatch turns out that if we have MITM Flag on it sends No IP Match and Command Failed.

So the response is right our Message should say something about IPMAtch MITM Spoof when this happens vs a generic Command Failed error like we we are showing (all the time)

**Comment by alexhauser** [comment]
Thanks for the pointer, @josegomez! 

I've read all the docs regarding MITM protection and CPS but must have missed the stuff about the "noiptest" flag, sorry! I know how to proceed now, though! Thanks again!

**Comment by josegomez** [comment]
> Thanks for the pointer, @josegomez!
> 
> I've read all the docs regarding MITM protection and CPS but must have missed the stuff about the "noiptest" flag, sorry! I know how to proceed now, though! Thanks again!

One more thing I noticed while doing this research apparently we are only  supposed to send in CPS Option flag is we have an established / pending CPS session (already)
![image](https://user-images.githubusercontent.com/420837/81317317-b2d54880-905a-11ea-932d-60ef8583fa83.png)

Currently our SQRL Options are hard coded in line 333
https://github.com/sqrldev/SQRLDotNetClient/blob/d43ebab283ac17d5638c5dfe95f17e30c58fede9/SQRLDotNetClientUI/ViewModels/AuthenticationViewModel.cs#L333

To always send CPS and SUK not sure if part of this issue (I can make a new issue for it) or not but perhaps we should check we have a Pending CPS before we send the CPS flag on the opts to comply with the spec?

**Comment by alexhauser** [comment]
I will look into this @josegomez, since I'm deep into the CPS stuff right now anyway.

**Comment by alexhauser** [comment]
> One more thing I noticed while doing this research apparently we are only supposed to send in CPS Option flag is we have an established / pending CPS session (already)

@josegomez, doing a little testing on this using GRC's diagnostics page https://www.grc.com/sqrl/diag.htm, it seems to me that Steve's client is doing exactly the same as we do, which is adding the `cps` option to each and every query, also to the very first one:

![opts](https://user-images.githubusercontent.com/4005543/81477115-3ab38200-9216-11ea-85cf-b0118fabc550.PNG)


So I guess we can leave that as is. 
What do you think?

**Comment by josegomez** [comment]
Evening if CPS isn’t established? 🤔

**Comment by alexhauser** [comment]
Yep. I mean, we can do it only on the `ident` command as well, I had that running without any problems already. But since Steve is also sending the `cps` option right from the beginning, I would tend to leave it as is.

**Comment by alexhauser** [comment]
OK, I think I know what's going on now. Will explain in the upcoming PR.
