### ISSUE TITLE
Bug with update check on changing language

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#144]
Upon manually changing the language in the client, the "new version available" button gets shown, even if no update is available.

Also, the button is shown for a short moment when launching the client and then disappears when the update check completes. Maybe we can get rid of this too, since it looks a little weird.

**Comment by josegomez** [comment]
haha I'm confused as to why changing the language breaks the button behavior hahaha! 
Actually that second "glitch" came in quite handy during testing, if you time it just right you can click the button even if there is no update which helps with testing 😂

That's how I tested that my command line params works since we can't publish a release. Click ninja!

You call it a bug I call it a convenient feature 😉 LoL

**Comment by alexhauser** [comment]
> haha I'm confused as to why changing the language breaks the button behavior hahaha!

Probably because we need to instantiate a new `MainMenuViewModel` to apply the language change.


> Actually that second "glitch" came in quite handy during testing, if you time it just right you can click the button even if there is no update which helps with testing 
> 
> That's how I tested that my command line params works since we can't publish a release. Click ninja!
> 
> You call it a bug I call it a convenient feature  LoL

🤣👍🏻
