### ISSUE TITLE
Project dead?

### ISSUE THREAD

**Issue by JiCiT** [sqrldev/SQRLDotNetClient#211]
Is this or any of the SQRL projects still active?  Looks like everything came to a halt around July 2020.

**Comment by josegomez** [comment]
hi @JiCiT no it is not quite "dead" just haven't done much work on it since because well pandemic hit and we got busy. Plus steve seems to have wondered off quasy permanently etc. So its here and both me and @alexhauser are still around and active in general just not actively doing improvements at the moment.

**Comment by JiCiT** [comment]
Thanks @josegomez.  So, it'll just stay beta for while. :-)
