### ISSUE TITLE
Improve identity management

### ISSUE THREAD

**Issue by alexhauser** [sqrldev/SQRLDotNetClient#29]
The way identity loading and selection works at the moment is very limited. I'd like to add a (static or at least singleton) `IdentityManager` class that could handle all of the following:

- Platform-aware loading of multiple identities stored in the respective standard location 
(e.g. `%USERPROFILE%\Documents\SQRL` on Windows)
- Keeping track of changes in the file system (e.g. for dynamically loading an identity which was copied into the identities directory without restarting the app)
- Populate the `IdentityName` and `FileName` properties of identities while loading them
- Changing the currently active identity / switching between identites
- Remembering last active identity 
- All other identity-management-related tasks that don't come to mind right now ;-)

Once this is done, we could implement a reusable UI widget for selecting/changing identites which could then be used wherever needed.

@josegomez, any thoughts or objections?

**Comment by josegomez** [comment]
There's a SQL lite DB which I already use to "remember" the last active identity, I have no problem with these changes but maybe we can leverage that, frankly if we wanted to we could store the whole identity there instead of the file system which can be capricious and un-predictiable.

Basically when an identity is imported or created, we store it in the DB and allow Export to file as needed? Not sure if that's better or not seems a little cleaner and gives us a little more control of the process?

Either way I'm fine with improving the current mechanism, which is very simplistic

**Comment by alexhauser** [comment]
Thanks Jose, I am aware of the SQLite database, and it would indeed be a viable alternative to use it exclusively as an identity store and ditch the whole file system approach.

I'll give it some more thought and get back to you.

**Comment by alexhauser** [comment]
Random thoughts that came to mind while thinking a little more about this:

- Database has the advantage of us fully controlling what happens with identities, since import and export are the only ways in/out
- Database has the advantage of being platform-agnostic, while file system would probably need some platform-dependent code
- Database is a little more complex and requires more maintainence (upgrades/migrations...), file system would be rather straightforward
- File system has the advantage that backups of the "my documents" folder would also include the sqrl identities
- Database is probably more user friendly in the end, since it's completely out of the user's sight and control, while an unwitting user might find the .sqrl files in their documents folder and think "_what are those strange files, I don't think I need those anymore..._" and delete them

So, not sure yet, but probably leaning more towards the database solution at the moment.

**Comment by josegomez** [comment]
Yeah I like the Db option better myself I like removing the operating / file system from the equation I'm already having to do some gymnastics around it and its a pain.
Particularly permissions are gnarly and could bite us in the rear end and as you stated users will just go delete random files and could find themselves without an identity randomly.

And if the database is in place and we are using Entity Framework (which we are) we could easily in the future switch to something like an azure and aws managed Db and provide "cloud" synchronization with little to no effort, I know steve and some others are big into "paper" and  "hard copies" but in reality users are going to be users and nobody wants to be 50 miles away from home and have no access to their stuff because their indentity is locked in their home PC and they forgot to upload it to their phone / laptop etc.

**Comment by alexhauser** [comment]
Very good points, @josegomez, I think I'll go with the database solution then!
