### ISSUE TITLE
Add Unlock and Remove Functionality to Authentication

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#40]
Currently we can Lock / Disable SQRL but there is no unlock or remove feature implemented. This is mostly due to the need for the Rescue Code which wasn't available (UI) at the time.
I believe @alexhauser  has provided a UI prompt for these scenarios which means we can revisit this feature and fix soon.

**Comment by josegomez** [comment]
I'll take this next, however I'll wait till PR #35 is Merged to Start

**Comment by alexhauser** [comment]
HA! @josegomez, assuming you have already started working on this one, and since I got in with #42 first, you'll be the one who has to do all the annoying rebasing/merging ;-)

Jokes aside, I hope you find my changes to the auth dialog are worth the trouble. But I guess it's all really well structured at this point and rebasing your unlock/remove changes to my updates shouldn't be too much of a hassle.

**Comment by josegomez** [comment]
They are awesome @alexhauser merge it and I'll rebase (haha story of my life, no worries)

**Comment by alexhauser** [comment]
Just merged #42 @josegomez, looking forward to seeing your additional protocol features put in!

**Comment by josegomez** [comment]
Solved by #44
