### ISSUE TITLE
Write our own MessageBox Implementation to allow for Localization

### ISSUE THREAD

**Issue by josegomez** [sqrldev/SQRLDotNetClient#47]
As noted in #45 we need to write our own messagebox implementation to fix a few bugs including allowing localization for messages.

**Comment by josegomez** [comment]
I'll tackle this

**Comment by josegomez** [comment]
So @alexhauser a bit of thought here, I've been working on this and failing miserably because Avalonia (thus far) doesn't do great with dynamic window sizing across multiple-platforms.

Would you be ok if we just make a standard message box size for this application? I was trying to make it dynamic but when it works well in windows it fails in nix and vise versa

Maybe we can have MessageBoxSmall, MessageBoxMedium and MessageBoxLarge?

**Comment by alexhauser** [comment]
> Would you be ok if we just make a standard message box size for this application? 

Sure, no problem @josegomez! I've also experienced that Avalonia can be a little frustrating when it comes to sizing/positioning etc. Probably not even their fault, since the layout-/window-managers are so vastly different on each platform.

> Maybe we can have MessageBoxSmall, MessageBoxMedium and MessageBoxLarge?

Yeah, that would probably take away the greatest pain of having to use a "one size fits all" messagebox. Would you implement this as an optional parameter in the constructor taking an enum which handles the three sizes?

**Comment by josegomez** [comment]
Yeah maybe default to medium and have the option to change it on the constructor.

**Comment by alexhauser** [comment]
By the way @josegomez, do you already have confirmation that the "_main form losing focus after opening and closing a dialog window_" was really caused by the old messagebox implementation? I think I might have seen this behaviour elsewhere while testing yesterday - without the involvement of the old messagebox - but I can't recall what I did to provoke it.

**Comment by josegomez** [comment]
@alexhauser no I haven't confirmed (or denied) this yet. Was working on getting a new messagebox before I replaced the old one. I'll do some testing maybe its the fact of invoking a window (at all)

**Comment by josegomez** [comment]
@alexhauser  I verified it is indeed the messagebox and it does'nt happen with the new one.

**Comment by josegomez** [comment]
This has been resolved by #53 waiting for review to merge / close

**Comment by josegomez** [comment]
Merged
